# -*- coding: utf-8 -*-
"""32 original development recipes. Metric values are clearly-estimated
approximations pending standardized weighing during kitchen testing.
All measurements US + metric. No macros, yields, or shelf-life stated as fact.
"""

# Each recipe dict keys:
# n, chap, icon, title, yield_, time, ingredients[(us,metric)], steps[],
# child, adult, flavor, allergens, age, activity, sub, test
RECIPES = [
# ============================================ CH5 FROZEN & FRUITY (5)
dict(n=1, chap=5, icon="pop", title="Creamy Mango Yogurt Pops",
 yield_="about 8 small pops (estimated)", time="10 min + freezing",
 ingredients=[("2 cups frozen mango chunks","~300 g"),("1 cup plain yogurt","~245 g"),
   ("1 tsp vanilla","5 ml"),("1–2 Tbsp water, only if needed","15–30 ml")],
 steps=["Blend the mango, yogurt, and vanilla until smooth, adding water only if the blender needs help.",
   "Divide among pop molds, add sticks, and freeze until firm."],
 child="Measure the yogurt and fill the molds with a small ladle.",
 adult="Runs the blender, places the sticks, and manages the freezer.",
 flavor="Cool, thick, and creamy with a bright mango tang.",
 allergens="Milk. Use a plain unsweetened dairy-free yogurt if that already fits the child's diet.",
 age="Let pops soften 1–2 minutes so they are easy to bite. Adult decides the safe size for the child.",
 activity="Colour Watch: notice how the orange mango and white yogurt swirl into one shade. Guess the new colour before blending.",
 sub="Swap mango for frozen peaches or pineapple.",
 test="Test sweetness, how easily the pops unmold, and the real number of pops."),

dict(n=2, chap=5, icon="snow", title="Blueberry Frozen-Yogurt Cereal Bark",
 yield_="about 8 pieces (estimated)", time="10 min + freezing",
 ingredients=[("2 cups plain yogurt","~490 g"),("1 cup blueberries, halved or lightly mashed","~150 g"),
   ("1/2 cup crunchy oat cereal","~30 g"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Stir the vanilla into the yogurt and spread it about 1 cm thick on a lined tray.",
   "Scatter the blueberries and cereal on top, then freeze until firm and break into age-appropriate pieces."],
 child="Spread the yogurt with the back of a spoon and arrange the fruit in a pattern.",
 adult="Halves the blueberries, manages the freezer, and breaks the bark into safe sizes.",
 flavor="Crackly, cold, and lightly sweet with pops of berry.",
 allergens="Milk; cereal may contain wheat or other allergens — read the box.",
 age="Halved berries reduce choking risk. Break bark small; hard frozen edges need a moment to soften.",
 activity="Pattern Lab: make stripes, spots, or a smiley. Which pattern is easiest to break evenly?",
 sub="Use raspberries or chopped strawberries instead of blueberries.",
 test="Validate spread thickness, thaw time, and how easily children can bite a piece."),

dict(n=3, chap=5, icon="snow", title="Watermelon-Mint Granita",
 yield_="about 4 small cups (estimated)", time="15 min + freezing (stir every 30 min)",
 ingredients=[("4 cups seedless watermelon cubes","~600 g"),("1 tsp lime juice","5 ml"),
   ("4–6 small mint leaves","a few"),("1 tsp honey, optional*","5 ml")],
 steps=["Blend the watermelon, lime, and mint until smooth, then pour into a shallow dish.",
   "Freeze, and every 30 minutes scrape with a fork to make icy flakes, until fully frozen and fluffy."],
 child="Scrape the freezing mixture with a fork to build the icy flakes.",
 adult="Blends, handles the freezer, and cuts any large watermelon pieces first.",
 flavor="Light, refreshing, and slushy with a whisper of mint.",
 allergens="None expected in the base — always confirm each label.",
 age="*Honey is not for children under 12 months. Serve small, soft flakes.",
 activity="Texture Timeline: draw the mixture at 0, 1, and 2 hours. How does liquid become flakes?",
 sub="Swap watermelon for cantaloupe or strawberries.",
 test="Confirm scrape timing, flake texture, and final flavour balance."),

dict(n=4, chap=5, icon="pop", title="Two-Ingredient Banana Nice-Cream",
 yield_="about 4 small servings (estimated)", time="5 min + freezing bananas ahead",
 ingredients=[("3 ripe bananas, sliced and frozen","~330 g"),("2–3 Tbsp milk of choice","30–45 ml"),
   ("1/4 tsp vanilla, optional","1 ml")],
 steps=["Blend the frozen banana slices with a splash of milk, scraping down as needed.",
   "Blend until it turns thick and creamy like soft ice cream; serve right away or freeze briefly to firm."],
 child="Add the banana slices and count the tablespoons of milk.",
 adult="Runs the blender or food processor and checks the final texture.",
 flavor="Sweet, smooth, and soft-serve creamy — all from fruit.",
 allergens="Milk if using dairy; choose a familiar dairy-free milk if preferred.",
 age="Serve soft. Freeze bananas fully ahead so the blend is smooth, not chunky.",
 activity="Change Watch: notice how hard frozen banana becomes creamy. What made it change?",
 sub="Add a spoon of cocoa or a few berries for a new flavour.",
 test="Test milk amount for smoothness and the best serving temperature."),

dict(n=5, chap=5, icon="pop", title="Yogurt-Dipped Banana Coins",
 yield_="about 20 coins (estimated)", time="10 min + freezing",
 ingredients=[("2 bananas, sliced into coins","~220 g"),("3/4 cup plain yogurt","~185 g"),
   ("1/2 tsp vanilla","2.5 ml"),("2 Tbsp crushed oat cereal, optional","~10 g")],
 steps=["Stir vanilla into the yogurt. Dip each banana coin to coat and set on a lined tray.",
   "Sprinkle with cereal if you like, then freeze until firm."],
 child="Dip the coins with a fork and sprinkle the topping.",
 adult="Slices the bananas to a safe thickness and manages the freezer.",
 flavor="Creamy-frozen outside, soft banana inside.",
 allergens="Milk; cereal may contain wheat or other allergens.",
 age="Cut coins to a size and thickness suitable for the child; let soften slightly before eating.",
 activity="Count & Estimate: guess how many coins you can make, then count. Were you close?",
 sub="Roll in finely crushed freeze-dried strawberries instead of cereal.",
 test="Confirm coin thickness, coating that stays on, and easy biting."),

# ============================================ CH6 YOGURT / PUDDING / CREAMY (5)
dict(n=6, chap=6, icon="cup", title="Strawberry Cheesecake Cups",
 yield_="about 4 small cups (estimated)", time="15 min",
 ingredients=[("1 1/2 cups thick plain yogurt","~370 g"),("1 cup chopped strawberries","~150 g"),
   ("4 graham crackers, crushed","~60 g"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Stir the vanilla into the yogurt.",
   "Layer yogurt and strawberries in small cups; add the crumbs just before serving so they stay crunchy."],
 child="Build the layers and choose the order.",
 adult="Chops the strawberries small and checks every label.",
 flavor="Cool and creamy with a soft crunch and berry sweetness.",
 allergens="Milk and wheat; exact allergens vary by cracker brand.",
 age="Chop strawberries small. Add crumbs at serving so texture stays easy.",
 activity="Layer Map: draw your cup from bottom to top. Which layer is thickest?",
 sub="Use crushed plain oat cereal instead of graham crackers for a wheat swap to verify.",
 test="Validate cup size, layer texture, and the right amount of crumb."),

dict(n=7, chap=6, icon="cup", title="Smooth Cocoa Chia Pudding",
 yield_="about 4 small servings (estimated)", time="10 min + 2 hours chilling",
 ingredients=[("1/4 cup chia seeds","~40 g"),("1 cup milk of choice","240 ml"),
   ("2 Tbsp unsweetened cocoa","~12 g"),("1 ripe banana","~110 g"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Blend all ingredients until the chia is fully broken down and smooth.",
   "Chill at least 2 hours, then stir and check the texture before serving."],
 child="Add ingredients with measuring cups and spoons.",
 adult="Runs the blender and decides if the texture suits the child.",
 flavor="Silky, chocolatey, and gently sweet from banana.",
 allergens="Milk depends on the drink chosen — check every label.",
 age="Blending smooths the chia. Confirm a texture the child manages comfortably.",
 activity="Thickness Test: check at 10 minutes and 2 hours. Draw how the spoon stands up.",
 sub="Use any familiar milk; oat or soy milk both work.",
 test="Test thickness, texture acceptance, and the final portion size."),

dict(n=8, chap=6, icon="cup", title="Chilled Cocoa-Avocado Cream",
 yield_="about 4 small servings (estimated)", time="10 min + 30 min chilling",
 ingredients=[("2 ripe avocados","~250 g flesh"),("1 ripe banana","~110 g"),
   ("3 Tbsp unsweetened cocoa","~18 g"),("1/3 cup milk of choice","80 ml"),("1 tsp vanilla","5 ml")],
 steps=["Blend everything until completely smooth, scraping the sides as needed.",
   "Chill 30 minutes and serve in small portions."],
 child="Scoop the avocado flesh with a spoon and count the measures.",
 adult="Halves the avocados, removes the pits, and runs the blender.",
 flavor="Rich, mousse-like, and deeply chocolatey.",
 allergens="Milk depends on the drink chosen.",
 age="Blend fully smooth. Serve small portions; texture is soft and spoonable.",
 activity="Colour Surprise: guess the colour before and after adding cocoa. What happened to the green?",
 sub="Swap banana for a very ripe pear for a different sweetness.",
 test="Evaluate colour, aftertaste, thickness, and serving size."),

dict(n=9, chap=6, icon="cup", title="Peach-Vanilla Yogurt Parfait",
 yield_="about 3 small cups (estimated)", time="12 min",
 ingredients=[("1 1/2 cups plain yogurt","~370 g"),("1 cup soft chopped peaches","~160 g"),
   ("1/2 cup rolled oats, toasted and cooled","~45 g"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Stir vanilla into the yogurt. Cool the toasted oats fully.",
   "Layer yogurt, peaches, and oats in small cups and serve."],
 child="Spoon the layers and sprinkle the cooled oats.",
 adult="Toasts and cools the oats and chops the peaches small.",
 flavor="Creamy, fruity, and lightly nutty from toasted oats.",
 allergens="Milk; oats may have cross-contact with wheat.",
 age="Use soft ripe peaches chopped small; make sure oats are cool and not clumped.",
 activity="Smell First: sniff the peaches, then the vanilla. Which words describe each aroma?",
 sub="Use canned peaches in juice (drained) when fresh are out of season.",
 test="Confirm oat toasting time, peach softness, and layer balance."),

dict(n=10, chap=6, icon="bowl", title="Golden Mango-Coconut Pudding (Dairy-Free option)",
 yield_="about 4 small servings (estimated)", time="10 min + 1 hour chilling",
 ingredients=[("2 cups frozen mango, thawed","~300 g"),("3/4 cup coconut milk drink","180 ml"),
   ("2 Tbsp chia seeds","~20 g"),("1/4 tsp vanilla","1 ml")],
 steps=["Blend the mango and coconut milk until smooth, then stir in the chia seeds.",
   "Chill at least 1 hour until set, stir, and serve in small cups."],
 child="Stir in the chia seeds and give it a taste-test smell.",
 adult="Runs the blender and checks the set texture before serving.",
 flavor="Tropical, creamy, and naturally golden.",
 allergens="Coconut; confirm the drink's full label. This version avoids dairy — verify all brands.",
 age="Let it set fully so chia is soft, not crunchy. Serve smooth and spoonable.",
 activity="Two-Milk Compare: try it once with coconut and once with dairy milk. Notice the taste difference.",
 sub="Use dairy milk if coconut is not preferred.",
 test="Confirm chia amount for a soft set and check the dairy-free flavour."),

# ============================================ CH7 MUFFINS / BITES / SMALL BAKES (5)
dict(n=11, chap=7, icon="cookie", title="Baked Banana Oat Bites",
 yield_="about 12 bites (estimated)", time="10 min + 16–20 min baking",
 ingredients=[("2 ripe bananas","~220 g"),("1 1/2 cups rolled oats","~135 g"),
   ("1 egg","1"),("1/2 tsp cinnamon","2.5 ml"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Heat oven to 350°F (175°C). Mash the banana and mix in everything else.",
   "Drop spoonfuls onto a lined sheet and bake until the centers are fully cooked."],
 child="Mash the banana and stir the mixture with a spoon.",
 adult="Handles the oven and pan and confirms the egg is fully cooked through.",
 flavor="Soft, warm, lightly spiced and gently sweet.",
 allergens="Egg. Oats may have cross-contact with wheat.",
 age="Cool before serving; make sure centers are set. Recipes with egg must be fully cooked.",
 activity="Before/After: draw one spoonful of batter and one baked bite. What changed with heat?",
 sub="Add a spoon of unsweetened cocoa for a chocolate version.",
 test="Confirm bake time, bite size, cooled texture, and real yield."),

dict(n=12, chap=7, icon="muffin", title="Carrot-Orange Mini Muffins",
 yield_="about 18 mini muffins (estimated)", time="15 min + 14–18 min baking",
 ingredients=[("1 cup finely grated carrot","~110 g"),("1 1/2 cups oat flour","~135 g"),
   ("2 eggs","2"),("1 ripe banana","~110 g"),("1/2 cup milk","120 ml"),
   ("finely grated zest of 1 orange","1 orange"),("1 tsp baking powder","5 ml")],
 steps=["Heat oven to 350°F (175°C) and line a mini-muffin pan.",
   "Mix the wet ingredients, fold in the dry, spoon into cups, and bake until the centers are cooked."],
 child="Mix the batter and place the liners in the pan.",
 adult="Grates the carrot and zest, handles the oven, and confirms doneness.",
 flavor="Moist, fragrant, and sunny with orange aroma.",
 allergens="Egg and milk; oats may have cross-contact with wheat.",
 age="Serve cooled; mini size suits small hands. Confirm centers are set.",
 activity="Aroma Hunt: smell the orange zest. Write three words for the smell before baking.",
 sub="Use grated apple in place of carrot.",
 test="Adjust moisture, time, and yield for your specific pan."),

dict(n=13, chap=7, icon="muffin", title="Blueberry-Lemon Mini Muffins",
 yield_="about 18 mini muffins (estimated)", time="15 min + 14–18 min baking",
 ingredients=[("1 1/2 cups oat flour","~135 g"),("2 eggs","2"),("1 ripe banana","~110 g"),
   ("1/3 cup milk","80 ml"),("3/4 cup blueberries","~110 g"),
   ("zest of 1 lemon","1 lemon"),("1 tsp baking powder","5 ml")],
 steps=["Heat oven to 350°F (175°C) and line a mini-muffin pan.",
   "Mix wet, fold in dry and zest, gently stir in blueberries, and bake until set."],
 child="Fold in the blueberries gently so they do not squash.",
 adult="Zests the lemon, handles the oven, and confirms doneness.",
 flavor="Bright, tender, and dotted with juicy berries.",
 allergens="Egg and milk; oats may have cross-contact with wheat.",
 age="Serve cooled. Whole small berries in soft muffin are usually fine; adult judges for the child.",
 activity="Count the Berries: estimate berries per muffin, then break one open and count.",
 sub="Use chopped strawberries instead of blueberries.",
 test="Confirm berry distribution, bake time, and cooled crumb."),

dict(n=14, chap=7, icon="cookie", title="No-Bake Apple-Cinnamon Oat Bites",
 yield_="about 14 bites (estimated)", time="15 min + 30 min chilling",
 ingredients=[("1 1/2 cups rolled oats","~135 g"),("1/2 cup finely grated apple, squeezed dry","~60 g"),
   ("1/3 cup sunflower seed butter","~85 g"),("2 Tbsp honey*","30 ml"),("1/2 tsp cinnamon","2.5 ml")],
 steps=["Mix everything into a soft dough that holds together when pressed.",
   "Roll into small balls with clean hands and chill until firm."],
 child="Roll the dough into balls with clean hands.",
 adult="Grates and squeezes the apple and checks the seed-butter label.",
 flavor="Chewy, apple-sweet, and warmly spiced — no oven needed.",
 allergens="Seeds; oats may have cross-contact with wheat. Confirm all brands.",
 age="*Honey is not for children under 12 months. Roll to a safe, soft size.",
 activity="Squeeze Science: notice how much liquid comes out of grated apple. Why do we remove it?",
 sub="Swap seed butter for a smooth nut butter if there is no allergy concern.",
 test="Confirm the dough holds, the size is safe, and the real yield."),

dict(n=15, chap=7, icon="muffin", title="Pumpkin Spice Mini Muffins",
 yield_="about 18 mini muffins (estimated)", time="15 min + 15–18 min baking",
 ingredients=[("1 cup pumpkin puree","~245 g"),("1 1/2 cups oat flour","~135 g"),
   ("2 eggs","2"),("1 ripe banana","~110 g"),("1 tsp cinnamon","5 ml"),
   ("1/4 tsp ginger","1 ml"),("1 tsp baking powder","5 ml")],
 steps=["Heat oven to 350°F (175°C) and line a mini-muffin pan.",
   "Mix wet, fold in dry and spices, spoon into cups, and bake until the centers spring back."],
 child="Stir the spices in and smell the warm aroma.",
 adult="Handles the oven and confirms centers are cooked.",
 flavor="Cozy, soft, and spiced like autumn.",
 allergens="Egg; oats may have cross-contact with wheat.",
 age="Serve cooled; mini size for small hands.",
 activity="Spice Sniff: smell cinnamon and ginger separately. Which is warmer? Which is sharper?",
 sub="Use mashed sweet potato in place of pumpkin.",
 test="Adjust spice level, bake time, and yield for your pan."),

# ============================================ CH8 WARM FRUIT DESSERTS (4)
dict(n=16, chap=8, icon="apple", title="Warm Cinnamon Apples with Crumble",
 yield_="about 4 servings (estimated)", time="12 min + 25–30 min baking",
 ingredients=[("3 apples, peeled if desired","~450 g"),("1/2 cup rolled oats","~45 g"),
   ("2 Tbsp melted butter","~28 g"),("1 tsp cinnamon","5 ml"),("1 Tbsp brown sugar, optional","~12 g")],
 steps=["Heat oven to 375°F (190°C). Cut the apples into small cubes.",
   "Mix oats, butter, and cinnamon, spoon over the fruit, and bake until tender and golden."],
 child="Mix the crumble topping and smell the cinnamon.",
 adult="Cuts the fruit, handles the oven, and checks that pieces are soft.",
 flavor="Warm, tender apple under a toasty oat crumble.",
 allergens="Milk if butter is used; substitute only with a familiar, suitable option.",
 age="Cut apples small and bake until soft. Let cool from hot to warm before serving.",
 activity="Hot vs. Warm: feel the bowl (adult helps). Why do we wait before tasting?",
 sub="Use melted coconut oil instead of butter for a dairy-free topping to verify.",
 test="Validate cut size, tenderness, and topping-to-fruit ratio."),

dict(n=17, chap=8, icon="apple", title="Individual Pear Oat Cakes",
 yield_="about 2 small cakes (estimated)", time="10 min + 18–22 min baking",
 ingredients=[("1 ripe pear, grated","~150 g"),("1 egg","1"),("2/3 cup rolled oats","~60 g"),
   ("1/4 cup milk","60 ml"),("1/2 tsp cinnamon","2.5 ml"),("1/2 tsp baking powder","2.5 ml")],
 steps=["Heat oven to 350°F (175°C). Mix and divide between two greased ramekins.",
   "Bake until the centers are set, then let cool until just warm."],
 child="Mix the batter and portion it with a spoon.",
 adult="Grates the pear, handles the oven, and checks temperature before serving.",
 flavor="Soft, cozy, and gently sweet with warm pear.",
 allergens="Egg and milk; oats may have cross-contact with wheat.",
 age="Cool from hot to warm; confirm centers are cooked. Egg recipes must be fully cooked.",
 activity="Portion Practice: try to split the batter evenly. Which cake looks bigger?",
 sub="Use grated apple instead of pear.",
 test="Validate ramekin size, bake time, and interior texture."),

dict(n=18, chap=8, icon="apple", title="Baked Cinnamon Peaches",
 yield_="about 4 servings (estimated)", time="10 min + 18–22 min baking",
 ingredients=[("4 ripe peaches, halved and pitted","~500 g"),("1/4 cup rolled oats","~22 g"),
   ("1 tsp cinnamon","5 ml"),("1 Tbsp melted butter","~14 g"),("2 tsp honey*, optional","10 ml")],
 steps=["Heat oven to 375°F (190°C). Place peach halves cut-side up in a dish.",
   "Top with oats, cinnamon, and butter and bake until soft and fragrant."],
 child="Sprinkle the oats and cinnamon into each peach hollow.",
 adult="Halves and pits the peaches and handles the oven.",
 flavor="Juicy, soft, and warmly spiced.",
 allergens="Milk if butter is used. *Honey not for under 12 months.",
 age="Serve warm, not hot. Cut into small pieces suited to the child after baking.",
 activity="Juice Watch: look at the peach before and after baking. Where did the juice come from?",
 sub="Use nectarines or plums instead of peaches.",
 test="Confirm bake time, softness, and topping amount."),

dict(n=19, chap=8, icon="berry", title="Warm Berry Oat Cobbler Cups",
 yield_="about 4 small cups (estimated)", time="12 min + 20–25 min baking",
 ingredients=[("2 cups mixed berries","~280 g"),("3/4 cup rolled oats","~68 g"),
   ("2 Tbsp oat flour","~12 g"),("2 Tbsp melted butter","~28 g"),("1/2 tsp cinnamon","2.5 ml")],
 steps=["Heat oven to 375°F (190°C). Divide berries among small oven-safe cups.",
   "Mix oats, oat flour, butter, and cinnamon; spoon over the berries and bake until bubbling and golden."],
 child="Spoon the oat topping over the berries.",
 adult="Handles the oven and hot cups and lets them cool to warm.",
 flavor="Jammy warm berries with a crisp oat lid.",
 allergens="Milk if butter is used; oats may have cross-contact with wheat.",
 age="Berries get very hot — cool well before serving and check for any large pieces.",
 activity="Bubble Count: watch the berries bubble (through the oven door). What makes them bubble?",
 sub="Use frozen berries; add a couple of extra minutes.",
 test="Confirm cup size, topping ratio, and safe serving temperature."),

# ============================================ CH9 COOKIES / BARS / SQUARES (6)
dict(n=20, chap=9, icon="cookie", title="Soft Pumpkin Oat Cookies",
 yield_="about 12 cookies (estimated)", time="12 min + 14–18 min baking",
 ingredients=[("1 cup pumpkin puree","~245 g"),("1 1/2 cups rolled oats","~135 g"),
   ("1 egg","1"),("2 Tbsp sunflower seed butter","~32 g"),("1 tsp cinnamon","5 ml")],
 steps=["Heat oven to 350°F (175°C). Mix and rest 5 minutes.",
   "Form small discs on a lined sheet and bake until cooked through."],
 child="Form discs with a spoon and the back of it.",
 adult="Checks the seed-butter label, handles the oven, and confirms doneness.",
 flavor="Soft, cakey, and mildly spiced.",
 allergens="Egg and seeds; check oats for cross-contact.",
 age="Cool before serving; confirm centers are set. Egg recipes must be fully cooked.",
 activity="Rest Test: notice the batter before and after resting 5 minutes. Did it thicken?",
 sub="Use mashed sweet potato instead of pumpkin.",
 test="Confirm the cookies hold together and check moisture after cooling."),

dict(n=21, chap=9, icon="cookie", title="Sweet-Potato Cocoa Squares",
 yield_="about 12 squares (estimated)", time="15 min + 20–26 min baking",
 ingredients=[("1 cup cooked mashed sweet potato","~250 g"),("1/2 cup seed or nut butter","~130 g"),
   ("1 egg","1"),("1/3 cup unsweetened cocoa","~30 g"),("1 ripe banana","~110 g"),
   ("1/2 tsp baking powder","2.5 ml")],
 steps=["Heat oven to 350°F (175°C) and line a small square pan.",
   "Mix, spread, and bake until the center is set; cool before cutting."],
 child="Mash the sweet potato and stir in the cocoa.",
 adult="Handles the oven and knife and verifies allergens and doneness.",
 flavor="Fudgy, rich, and deeply chocolatey.",
 allergens="Egg; nut or seed depending on the butter chosen.",
 age="Cool fully before cutting into small squares. Confirm the center is cooked.",
 activity="Mix Colour: watch orange sweet potato turn brown with cocoa. Predict the final colour.",
 sub="Use sunflower seed butter for a nut-free version to verify.",
 test="Confirm pan size, doneness, cutting, and cooled texture."),

dict(n=22, chap=9, icon="berry", title="Soft Strawberry Oat Truffles",
 yield_="about 12 balls (estimated)", time="15 min + 30 min chilling",
 ingredients=[("1 cup ground oats","~90 g"),("3/4 cup crushed freeze-dried strawberries","~20 g"),
   ("1/2 cup sunflower seed butter","~130 g"),("2–4 Tbsp milk, as needed","30–60 ml"),
   ("1/2 tsp vanilla","2.5 ml")],
 steps=["Mix into a soft dough that holds its shape, adding milk a little at a time.",
   "Roll into small balls with clean hands and chill before serving."],
 child="Roll the balls with clean hands.",
 adult="Adjusts texture, checks labels, and decides the appropriate size.",
 flavor="Chewy, berry-bright, and lightly sweet.",
 allergens="May contain milk, wheat, or seeds depending on brands.",
 age="Roll to a safe, soft size — not too firm or too large.",
 activity="Sticky Scale: rate the dough from 1 (dry) to 5 (sticky). Add milk to reach a 3.",
 sub="Use freeze-dried raspberries instead of strawberries.",
 test="Confirm cohesion, safe size, and actual yield."),

dict(n=23, chap=9, icon="cookie", title="Banana Oat Breakfast Cookies",
 yield_="about 10 cookies (estimated)", time="10 min + 14–16 min baking",
 ingredients=[("2 ripe bananas","~220 g"),("1 1/2 cups rolled oats","~135 g"),
   ("2 Tbsp raisins, optional","~18 g"),("1/2 tsp cinnamon","2.5 ml"),("1/4 tsp vanilla","1 ml")],
 steps=["Heat oven to 350°F (175°C). Mash bananas and mix in everything else.",
   "Drop spoonfuls onto a lined sheet, flatten slightly, and bake until set."],
 child="Mash the bananas and stir in the oats.",
 adult="Handles the oven and checks that they are set.",
 flavor="Chewy, wholesome, and naturally sweet — egg-free and dairy-free.",
 allergens="Oats may have cross-contact with wheat. Raisins can be a choking risk for the very young.",
 age="For younger children, chop or omit raisins. Adult decides based on the child.",
 activity="Two-Ingredient Wonder: banana + oats makes a cookie. What holds it together?",
 sub="Swap raisins for chopped soft dried apricots.",
 test="Confirm they hold together, the bake time, and cooled chew."),

dict(n=24, chap=9, icon="cookie", title="No-Bake Date-Oat Squares",
 yield_="about 12 squares (estimated)", time="15 min + 1 hour chilling",
 ingredients=[("1 cup soft pitted dates","~150 g"),("1 1/2 cups rolled oats","~135 g"),
   ("1/3 cup sunflower seed butter","~85 g"),("2 Tbsp milk of choice","30 ml"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Blend the dates into a paste, then mix with oats, seed butter, milk, and vanilla.",
   "Press firmly into a lined pan, chill until firm, and cut into small squares."],
 child="Press the mixture into the pan with clean hands or a spoon.",
 adult="Blends the dates, checks labels, and cuts the squares.",
 flavor="Chewy, caramel-sweet from dates, no oven needed.",
 allergens="Seeds; oats may have cross-contact with wheat.",
 age="Press firmly so squares hold. Cut small; dates are sticky — confirm easy chewing.",
 activity="Paste Power: watch whole dates become smooth paste. What machine helped, and who runs it?",
 sub="Use a smooth nut butter if there is no allergy concern.",
 test="Confirm the squares hold, the chew, and actual yield."),

dict(n=25, chap=9, icon="cookie", title="Soft Cocoa-Chip Oat Cookies",
 yield_="about 12 cookies (estimated)", time="12 min + 12–15 min baking",
 ingredients=[("2 ripe bananas","~220 g"),("1 1/2 cups rolled oats","~135 g"),
   ("2 Tbsp unsweetened cocoa","~12 g"),("2 Tbsp chocolate chips","~24 g"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Heat oven to 350°F (175°C). Mash bananas and mix in oats, cocoa, and vanilla.",
   "Stir in the chips, form small cookies, and bake until set."],
 child="Count and stir in the chocolate chips.",
 adult="Handles the oven and confirms doneness.",
 flavor="Soft, chocolatey, with little melty chips.",
 allergens="Chips may contain milk and soy; oats may have cross-contact with wheat.",
 age="Cool slightly so melted chips are not too hot. Serve small cookies.",
 activity="Chip Count: give each cookie the same number of chips. Practice fair sharing.",
 sub="Use raisins instead of chocolate chips.",
 test="Confirm chip amount, bake time, and cooled softness."),

# ============================================ CH10 BUILD-YOUR-OWN (3 frameworks)
dict(n=26, chap=10, icon="bowl", title="Build-Your-Own Yogurt Parfait Bar",
 yield_="varies — each person builds one cup", time="15 min set-up",
 ingredients=[("Base: plain yogurt","1 scoop per cup"),("Fruits: berries, chopped peach, banana coins","child's choice"),
   ("Crunch: toasted oats, crushed oat cereal","1 spoon"),("Aroma: vanilla, cinnamon, orange zest","a pinch")],
 steps=["Set out the bases, fruits, and crunch in small bowls with spoons.",
   "Each person layers their own cup, choosing order and amounts."],
 child="Choose ingredients and build their own layered cup.",
 adult="Chops fruit to safe sizes and sets up the station.",
 flavor="A different cup every time — you are the recipe designer.",
 allergens="Milk; crunch toppings may contain wheat. Label each bowl.",
 age="Chop all fruit small. Adult supervises choices and sizes.",
 activity="Design Sheet: draw your parfait and give it a name in the Build-Your-Own pages.",
 sub="Use dairy-free yogurt for a non-dairy bar.",
 test="Note favourite combinations and which toppings stay crunchy."),

dict(n=27, chap=10, icon="snow", title="Build-Your-Own Frozen Yogurt Bark",
 yield_="varies — one shared tray", time="15 min + freezing",
 ingredients=[("Base: plain yogurt + 1/2 tsp vanilla","spread on tray"),("Toppings: halved berries, banana coins","child's choice"),
   ("Crunch: crushed oat cereal","a sprinkle"),("Fun: a few chocolate chips","optional")],
 steps=["Spread the vanilla yogurt on a lined tray.",
   "Each person decorates their zone, then freeze and break into safe pieces."],
 child="Decorate their own zone of the tray with a pattern.",
 adult="Halves fruit, manages the freezer, and breaks bark to size.",
 flavor="A frozen canvas you design and then taste.",
 allergens="Milk; toppings may contain wheat or soy. Read labels.",
 age="Halve round fruit; break bark small. Let soften before biting.",
 activity="Zone Map: mark your zone on the tray and plan your pattern first.",
 sub="Skip chips for a simpler bark.",
 test="Note topping amounts that freeze and bite well."),

dict(n=28, chap=10, icon="bowl", title="Build-Your-Own Warm Fruit Bowl",
 yield_="varies — one bowl each", time="15 min + short bake",
 ingredients=[("Base: soft chopped apple, pear, or peach","1 scoop"),("Warmth: a little cinnamon","a pinch"),
   ("Crunch: oat crumble (oats + a little butter)","1 spoon"),("Finish: a spoon of plain yogurt","optional")],
 steps=["Each person fills a small oven-safe bowl with fruit and cinnamon.",
   "Adult bakes until soft; cool to warm, then add crunch and a spoon of yogurt."],
 child="Choose the fruit and sprinkle the cinnamon.",
 adult="Cuts fruit, handles the oven and hot bowls, and cools them to warm.",
 flavor="Cozy, soft fruit with a warm-spice smell.",
 allergens="Milk if butter/yogurt used; oats may have cross-contact with wheat.",
 age="Fruit and bowls get hot — cool well before tasting. Cut fruit small.",
 activity="Warm-Word List: after tasting, write three warm words for how it felt and smelled.",
 sub="Serve without baking as a fresh fruit bowl for a no-oven option.",
 test="Confirm fruit softness, safe temperature, and crumble amount."),

# ============================================ EXTRA RECIPES (reach 32)
dict(n=29, chap=6, icon="cup", title="Cocoa-Banana Smoothie Cups",
 yield_="about 3 small cups (estimated)", time="8 min",
 ingredients=[("2 ripe bananas","~220 g"),("1 cup milk of choice","240 ml"),
   ("1 Tbsp unsweetened cocoa","~6 g"),("1/2 cup plain yogurt","~120 g"),("1/4 tsp vanilla","1 ml")],
 steps=["Blend everything until smooth and frothy.",
   "Pour into small cups and serve right away, or chill briefly."],
 child="Add the ingredients and press the blender button with an adult.",
 adult="Supervises the blender and checks the texture.",
 flavor="Cool, creamy, and lightly chocolatey — like a thin milkshake.",
 allergens="Milk depending on the drink and yogurt chosen.",
 age="Serve in small cups; thickness is easy to sip or spoon.",
 activity="Froth Watch: notice the bubbles on top. Where did the air come from?",
 sub="Add a few frozen berries for a fruitier cup.",
 test="Test thickness, sweetness, and serving size."),

dict(n=30, chap=6, icon="cup", title="Vanilla Rice Pudding Cups",
 yield_="about 4 small cups (estimated)", time="10 min + 25–30 min cooking",
 ingredients=[("1/2 cup short-grain rice","~95 g"),("2 cups milk of choice","480 ml"),
   ("1 tsp vanilla","5 ml"),("1/2 tsp cinnamon","2.5 ml"),("1 Tbsp honey*, optional","15 ml")],
 steps=["Adult simmers the rice and milk gently, stirring often, until soft and creamy.",
   "Stir in vanilla and cinnamon, cool to warm, and spoon into small cups."],
 child="Measure the rice and stir in the vanilla once cooled a little.",
 adult="Manages the stove, stirs the hot pot, and cools it to a safe temperature.",
 flavor="Warm, soft, and comforting with gentle spice.",
 allergens="Milk depending on the drink chosen. *Honey not for under 12 months.",
 age="Serve warm, not hot. Soft, spoonable texture suits many ages; adult confirms.",
 activity="Grow Watch: measure the rice before and picture it after. Why did it get bigger?",
 sub="Use any familiar milk; oat milk makes it dairy-free (verify).",
 test="Confirm cook time, creaminess, and safe serving temperature."),

dict(n=31, chap=9, icon="berry", title="Berry Oat Crumble Bars",
 yield_="about 9 bars (estimated)", time="15 min + 25–30 min baking",
 ingredients=[("2 cups rolled oats","~180 g"),("1 cup oat flour","~90 g"),
   ("1/3 cup melted butter","~75 g"),("1 ripe banana, mashed","~110 g"),
   ("1 1/2 cups berries","~210 g"),("1/2 tsp cinnamon","2.5 ml")],
 steps=["Heat oven to 350°F (175°C). Mix oats, oat flour, butter, banana, and cinnamon into a crumbly dough.",
   "Press half in a lined pan, add berries, top with the rest, and bake until golden; cool before cutting."],
 child="Press the base and crumble the top layer over the berries.",
 adult="Melts the butter, handles the oven and knife, and cools before cutting.",
 flavor="Buttery oat layers with a jammy berry middle.",
 allergens="Milk; oats may have cross-contact with wheat.",
 age="Cool fully before cutting into small bars. Berry layer gets hot.",
 activity="Layer Count: how many layers can you see in a cut bar? Draw them.",
 sub="Use melted coconut oil for a dairy-free version to verify.",
 test="Confirm pan size, set middle, clean cutting, and cooled texture."),

dict(n=32, chap=9, icon="cookie", title="Oatmeal-Raisin Soft Cookies",
 yield_="about 12 cookies (estimated)", time="12 min + 12–15 min baking",
 ingredients=[("1 ripe banana","~110 g"),("1 egg","1"),("1 1/2 cups rolled oats","~135 g"),
   ("3 Tbsp raisins","~27 g"),("1 tsp cinnamon","5 ml"),("1/2 tsp vanilla","2.5 ml")],
 steps=["Heat oven to 350°F (175°C). Mash the banana and mix in everything else.",
   "Drop spoonfuls onto a lined sheet, flatten gently, and bake until set."],
 child="Count the raisins and stir the dough.",
 adult="Handles the oven and confirms the egg is fully cooked.",
 flavor="Chewy, spiced, and studded with sweet raisins.",
 allergens="Egg; oats may have cross-contact with wheat. Raisins can be a choking risk for the very young.",
 age="For younger children, chop or omit raisins. Cool before serving; egg must be fully cooked.",
 activity="Soak Test: soak a few raisins in warm water for 5 minutes. What changed?",
 sub="Swap raisins for chopped soft dried apricots.",
 test="Confirm bake time, chew, and cooled texture."),
]
